homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude_old
  longitude: !secret home_longitude_old
  elevation: !secret home_elevation_old
  unit_system: metric
  time_zone: !secret home_time_zone
  packages: !include_dir_merge_named includes/packages
  customize: !include_dir_merge_named includes/customize
#  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#

# Example configuration.yaml entry

frontend:
  themes: !include_dir_merge_named themes
  javascript_version: auto

#
lovelace:
  mode: yaml

#HASC
hacs:
  token: !secret HACS_github
  appdaemon: true
  python_script: true
  theme: true

# Text to speech
tts:
  - platform: google_translate

# Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight:  !include includes/yeelight.yaml
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_gateway2_corridor_mac
      key: !secret xiaomi_aqara_gateway2_corridor_key
      host: !secret xiaomi_aqara_gateway2_corridor_host

mikrotik:
  - name: Mikrotik
    host: !secret mikrotikRouter_host
    username: !secret mikrotikRouter_user
    password: !secret mikrotikRouter_pass
    arp_ping: true
    force_dhcp: true
    detection_time: 60

telegram_bot:
  - platform: polling
    api_key: !secret telegramm_bot_api_token
    allowed_chat_ids:
      - !secret telegramm_id_pv

notify:
  - name: telegramm_pv
    platform: telegram
    chat_id: !secret telegramm_id_pv

input_text: !include_dir_merge_named includes/inputs
#TODO    
#device_tracker:
#  - platform: snmp
#    host:
#    community: public
#    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
# IR Remote Control
# https://www.home-assistant.io/integrations/xiaomi_miio/#xiaomi-ir-remote
# model: chuangmi.remote.h102c01
remote: !include_dir_merge_list includes/smart_devices/ir_remote
  # - platform: xiaomi_miio
  #   host: !secret ir_remote_badroom_ip
  #   token: !secret ir_remote_badroom_token
  #   name: ir_remote_badroom

device_tracker: !include includes/device_tracker.yaml
media_player: !include_dir_merge_list includes/media_players