homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_time_zone
#  customize: !include_dir_merge_list includes/customize
#  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
#
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: auto

#
lovelace:
  mode: yaml

#HASC
hacs:
  token: !secret HACS_github
  appdaemon: true
  python_script: true
  theme: true

# Text to speech
tts:
  - platform: google_translate

# Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight:  !include includes/yeelight.yaml
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/scripts

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_aqara_gateway2_corridor_mac
      key: !secret xiaomi_aqara_gateway2_corridor_key
      host: !secret xiaomi_aqara_gateway2_corridor_host

mikrotik:
  - name: Mikrotik
    host: !secret mikrotikRouter_host
    username: !secret mikrotikRouter_user
    password: !secret mikrotikRouter_pass
    arp_ping: true
    force_dhcp: true
    detection_time: 60
#TODO    
#device_tracker:
#  - platform: snmp
#    host:
#    community: public
#    baseoid: 1.3.6.1.4.1.14988.1.1.1.2.1.1
