# Змінні
substitutions:
  location: bad_room
 
esphome:
  name: esp32_bad_room
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_common_ssid
  password: !secret wifi_common_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_esp32_ssid
    password: !secret wifi_esp32_pass

web_server:
  port: 80
  

# Інтервал сканування BLE
esp32_ble_tracker:

sensor:
# Час в онлайні
  - platform: uptime
    name: ${location}_esp32_uptime
    update_interval: 60s     

# Рівень сигнала шлюзу
  - platform: wifi_signal
    name:  ${location}_esp32_wifi
    update_interval: 60s

#Сенсори годинника Вітальня    
#  - platform: xiaomi_lywsd02
#    mac_address: !secret living_room_time_mac
#    temperature:
#      name: "LYWSD02_living_room_Temperature"
#    humidity:
#      name: "LYWSD02_living_room_Humidity"
#    battery_level:
#      name: "LYWSD02_living_room_battery_level"

#Сенсори годинника Спальня    
  - platform: xiaomi_lywsd02
    mac_address: !secret bed_room_time_mac
    temperature:
      name: "LYWSD02_bed_room_Temperature"
    humidity:
      name: "LYWSD02_bed_room_Humidity"
    battery_level:
      name: "LYWSD02_bad_room_battery_level"

# Версія прошивки
text_sensor:
  - platform: version
    name: ${location}_esp32_firmware_version
    icon: "mdi:information"
    
# кнопка перезапуска    
switch:
  - platform: restart
    name: ${location}_esp32_Restart

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota: