# Змінні
substitutions:
  location: bad_room
  update_interval: 60s
 
esphome:
  name: esp32_bad_room
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_common_ssid
  password: !secret wifi_common_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_esp32_ssid
    password: !secret wifi_esp32_pass

web_server:
  port: 80
  

# Інтервал сканування BLE
esp32_ble_tracker:

i2c:
  - id: bus_b
    sda: 26
    scl: 32
    scan: true

sensor:
# Час в онлайні
  - platform: uptime
    name: ${location}_esp32_uptime
    update_interval: ${update_interval}     

# Рівень сигнала шлюзу
  - platform: wifi_signal
    name:  ${location}_esp32_wifi
    update_interval: ${update_interval}
    
#ESP Hall Sensor    
  - platform: esp32_hall
    name: ${location}_esp32_hall_sensor
    update_interval: ${update_interval}

#Сенсори годинника Спальня    
  - platform: xiaomi_lywsd02
    mac_address: !secret bed_room_time_mac
    temperature:
      name: ${location}_LYWSD02_Temperature
    humidity:
      name: ${location}_LYWSD02_Humidity
    battery_level:
      name: ${location}_LYWSD02_battery_level

#Сенсори датчика ENV II - BMP-280
  - platform: bmp280
    i2c_id: bus_b
    address: 0x76
    temperature:
      name: ${location}_bmp280_Temperature
    pressure:
      name: ${location}_bmp280_Pressure
      oversampling: 16x
    update_interval: ${update_interval}

#Сенсори датчика ENV II - SHT30
  - platform: sht3xd
    i2c_id: bus_b
    address: 0x44
    temperature:
      name: ${location}_sht30_Temperature
    humidity:
      name: ${location}_sht30_Humidity
    update_interval: ${update_interval}

# Версія прошивки
text_sensor:
  - platform: version
    name: ${location}_esp32_firmware_version
    icon: "mdi:information"
    
# кнопка перезапуска    
switch:
  - platform: restart
    name: ${location}_esp32_Restart

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota: